config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "home", to: "pages#home"
  root "pages#home"

  resources :reviews, only: [:create]
  resources :requests, only: [:create]

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_service.rb
class ContactService < ApplicationRecord
end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id         :bigint           not null, primary key
#  date       :date
#  email      :string
#  end_time   :time
#  first_name :string
#  last_name  :string
#  message    :text
#  start_time :time
#  subject    :string
#  timezone   :string           default("Mexico City")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Request < ApplicationRecord
  SUBJECTS = ["",
    "Project Review",
    "General Programming Questions",
    "Ruby on Rails application review",
    "Programming Fundamentals",
    "Ruby on Rails Fundamentals",
    "Data Structures and Algorithms",
    "Interview Prep",
    "Other"].freeze

  AVAILABLE_TIMES = [1800, 1830, 1900, 1930, 2000, 2030, 2100, 2130, 2200].freeze

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :message, presence: true
  validates :message, length: {minimum: 25, maximum: 500}
  validates :subject, presence: true, inclusion: {in: SUBJECTS}
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :date, presence: true

  def unavailable_times
    times = {}
    self.class.all.map do |request|
      times[request.date] = [] if times[request.date].nil?
      times[request.date] << [request.start_time, request.end_time]
    end
    times
  end

  # def available_times
  #   available_times = []
  #   self.class::AVAILABLE_TIMES.each do |time|
  #     available_times << time if available_time?(time)
  #   end
  #   available_times
  # end

  # def available_time?(time)
  #   pry
  #   !self.class.all.any? do |request|
  #     request.date == date && request.start_time == time
  #   end
  # end
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :bigint           not null, primary key
#  email      :text
#  first_name :string
#  last_name  :string
#  message    :text
#  rating     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Review < ApplicationRecord
  RATINGS = ["",
    ["⭐️", 1],
    ["⭐️⭐️", 2],
    ["⭐️⭐️⭐️", 3],
    ["⭐️⭐️⭐️⭐️", 4],
    ["⭐️⭐️⭐️⭐️⭐️", 5]].freeze

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :message, presence: true
  validates :message, length: {minimum: 25, maximum: 500}
  validates :rating, presence: true, inclusion: {in: 1..5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  layout "errors"

  def not_found
    render status: :not_found
  end

  def internal_server_error
    render status: :internal_server_error
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @review = Review.new
    @request = Request.new
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :request_params, only: [:create]

  def create
    @request = Request.new(request_params)
    if @request.save
      RequestMailer.received_request(@request).deliver_now
      flash.now[:success] = {message: t(".success"), body: ""}
      @request = Request.new
      respond_to do |format|
        format.turbo_stream
      end
    else
      flash.now[:error] = {message: t(".error"), body: @request.errors.full_messages.join(", ")}
      render turbo_stream: turbo_stream.replace(:flash_messages, partial: "shared/flash_messages")
    end
  end

  private

  def request_params
    params.require(:request).permit(:first_name, :last_name, :email, :subject, :message, :date, :timezone, :start_time, :end_time)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :review_params, only: [:create]

  def create
    @review = Review.new(review_params)
    if @review.save
      flash.now[:success] = {message: t(".success"), body: ""}
      @review = Review.new
      respond_to do |format|
        format.turbo_stream
      end
    else
      flash.now[:error] = {message: t(".error"), body: @review.errors.full_messages.join(", ")}
      render turbo_stream: turbo_stream.replace(:flash_messages, partial: "shared/flash_messages")
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating, :email, :first_name, :last_name, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def decorate(model, decorate_class = nil)
    (decorate_class || "#{model.class}Decorator".constantize).new(model)
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Daniel Enqz</title>
    <%= favicon_link_tag 'profile/enqz-blue.webp', type: 'image/webp' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Daniel Enqz portfolio">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container relative mx-auto mt-7 xl:mt-14 px-5">
      <div class="fixed top-16 inset-x-5 md:inset-x-40 lg:inset-x-80 z-50">
        <%= render partial: "shared/flash_messages", locals: { flash: flash } %>
      </div>
      <%= render 'shared/desktop_breadcrumb' %>
      <div class="mt-10 h-screen grid content-start">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Daniel Enqz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">
      <%= yield(:error) %>
  </body>
</html>

app/views/pages/_tabs.html.erb
<div class="border-b border-gray-200">
  <nav class="-mb-px flex" aria-label="Tabs">
    <button id="request" data-tabs-target="tabButton" data-action="tabs#toggleTab" class="transition duration-700 ease-in-out border-pink-500 text-pink-600 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm">
      Schedule Class
    </button>

    <button id="review" data-tabs-target="tabButton" data-action="tabs#toggleTab" class="transition duration-700 ease-in-out border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm">
      Leave Review
    </button>
  </nav>
</div>

app/views/pages/home.html.erb
<div data-controller="tabs">
  <%# First tab is active by default (meaning it has active tab colors and tab is not hidden) %>

  <%= render "tabs" %>

  <%= turbo_frame_tag "request_tab" do %>
    <div class="overflow-hidden bg-white py-16 px-1 lg:px-8 lg:py-20 item-animate" data-tabs-target="requestTab">
      <%= render partial: "requests/new", locals: {request: @request} %>
    </div>
  <% end %>


  <%= turbo_frame_tag "review_tab" do %>
    <div class="relative bg-white hidden" data-tabs-target="reviewTab">
      <%= render partial: "reviews/new", locals: {review: @review} %>
    </div>
  <% end %>
</div>

app/views/pages/projects.html.erb
<div class="flex flex-wrap absolute left-40 md:left-60">
  <%= link_to home_path, class: "py-4 px-8 bg-white shadow-lg rounded-lg m-5" do %>
      <h2 class="text-gray-800 text-3xl font-semibold"> Projects </h2>
      <p class="mt-2 text-gray-600">This are my projects</p>
  <% end %>

  <%= link_to home_path, class: "py-4 px-8 bg-white shadow-lg rounded-lg m-5" do %>
      <h2 class="text-gray-800 text-3xl font-semibold"> Projects </h2>
      <p class="mt-2 text-gray-600">This are my projects</p>
  <% end %>

  <%= link_to home_path, class: "py-4 px-8 bg-white shadow-lg rounded-lg m-5" do %>
      <h2 class="text-gray-800 text-3xl font-semibold"> Projects </h2>
      <p class="mt-2 text-gray-600">This are my projects</p>
  <% end %>

  <%= link_to home_path, class: "py-4 px-8 bg-white shadow-lg rounded-lg m-5" do %>
      <h2 class="text-gray-800 text-3xl font-semibold"> Projects </h2>
      <p class="mt-2 text-gray-600">This are my projects</p>
  <% end %>

  <%= link_to home_path, class: "py-4 px-8 bg-white shadow-lg rounded-lg m-5" do %>
      <h2 class="text-gray-800 text-3xl font-semibold"> Projects </h2>
      <p class="mt-2 text-gray-600">This are my projects</p>
  <% end %>
</div>

app/views/requests/_new.html.erb
<div class="relative mx-auto max-w-xl">
  <%= render "requests/form_components/title" %>
  <div class="mt-12">
    <%= form_with model: request, url: requests_path, method: :post, local: true, class: "grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8", data: { controller: "form--validator" } do |f| %>
      <%= render partial: "requests/form_components/fields", locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/requests/create.turbo_stream.erb
<%= turbo_stream.replace "request_tab" do %>
  <%= turbo_frame_tag "request_tab" do %>
    <div class="overflow-hidden bg-white py-16 px-1 lg:px-8 lg:py-20" data-tabs-target="requestTab">
      <%= render partial: "requests/new", locals: {request: @request} %>
    </div>
  <% end %>
<% end %>

<%= turbo_stream.replace "flash_messages", partial: "shared/flash_messages" %>

app/views/requests/form_components/_calendar.html.erb
<div class="sm:col-span-2" data-controller="toggle">
  <div class="flex justify-between items-center">
    <%= f.label :date, "Let's Schedule! (CST) 📅", class: "block text-sm font-bold text-gray-700", data: { "toggle-target": "timeFeedback" } %>
    <%= f.hidden_field :timezone, data: { "toggle-target": "timezoneValue" } %>
  </div>
  <div class="flex items-center justify-between my-2">
    <span class="flex flex-grow flex-col">
      <p class="text-sm font-medium flex items-center text-gray-900" id="availability-label">
        <%= inline_svg_tag("extra/lock.svg", class: "text-gray-700 w-5 h-5 inline-block", aria_hidden: true) %>
        Your Privacy Matters
      </p>
      <span class="text-sm text-gray-500 ml-1" id="availability-description">Schedule class using my location.</span>
    </span>
    <button data-toggle-target="button" data-action="toggle#getUserLocation" type="button" class="bg-gray-200 relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" role="switch" aria-checked="false" aria-labelledby="availability-label" aria-describedby="availability-description">
      <span aria-hidden="true" data-toggle-target="span" class="translate-x-0 pointer-events-none h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out flex justify-center items-center">
        <%= inline_svg_tag("feedback/line-cross.svg", class: "text-gray-300 w-3 h-3 inline-block", aria_hidden: true, data: { "toggle-target": "cross" }) %>
        <%= inline_svg_tag("feedback/line-check.svg", class: "text-teal-300 w-3 h-3 inline-block hidden", aria_hidden: true, data: { "toggle-target": "check" }) %>
      </span>
    </button>
  </div>
  <div class="flatpickr-calendar-custom"
    data-controller="form--availability"
    <%= raise %>
    data-form--availability-used-days-value="<%= @request.unavailable_times.to_json %>"
    data-form--availability-default-day-hours-value="<%= Request::AVAILABLE_TIMES %>">
    <%= f.text_field :date,
      class: "block w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 shadow-md  transition ease-in-out delay-100",
      data: {
        controller: "flatpickr--calendar",
        "flatpickr--calendar-target": "input",
        "form--availability-target": "dateField",
        "action": "form--availability#validate" } %>
  </div>
</div>
<div>
  <div class="flex justify-between items-center">
    <%= f.label :start_time, "Start Time", class: "block text-sm font-bold text-gray-700" %>
    <p class="hidden text-sm font-bold text-emerald-400 item-animate-right">
      Valid
      <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
    </p>
  </div>
  <div class="mt-1">
    <%= f.select :start_time, decorate(@request).friendly_available_times, {}, class: "block w-full rounded-md  border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", id: "start-time-field" %>
  </div>
</div>
<div>
  <div class="flex justify-between items-center">
    <%= f.label :end_time, "End Time", class: "block text-sm font-bold text-gray-700" %>
    <p class="hidden text-sm font-bold text-emerald-400 item-animate-right">
      Valid
      <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
    </p>
  </div>
  <div class="mt-1">
    <%= f.select :end_time, decorate(@request).friendly_available_times, {}, class: "block w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", id: "end-time-field"  %>
  </div>
</div>

app/views/requests/form_components/_fields.html.erb
<div>
  <div class="flex justify-between items-center">
    <%= f.label :first_name, "First name", class: "block text-sm font-bold text-gray-700" %>
    <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
      Valid
      <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
    </p>
  </div>
  <div class="mt-1">
    <%= f.text_field :first_name, class: "block w-full rounded-md  border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", data: { "form--validator-target": "field firstName" } %>
  </div>
</div>
<div>
  <div class="flex justify-between items-center">
    <%= f.label :last_name, "Last name", class: "block text-sm font-bold text-gray-700" %>
    <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
      Valid
      <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
    </p>
  </div>
  <div class="mt-1">
    <%= f.text_field :last_name, class: "block w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", data: { "form--validator-target": "lastName" } %>
  </div>
</div>
<div class="sm:col-span-2">
  <div class="flex justify-between items-center">
    <%= f.label :subject, "Subject", class: "block text-sm font-bold text-gray-700" %>
    <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
      Valid
      <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
    </p>
  </div>
  <div class="mt-1">
    <%= f.select :subject, Request::SUBJECTS, {}, class: "block w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", data: { "form--validator-target": "field subject" } %>
  </div>
</div>
<div class="sm:col-span-2">
  <div class="flex justify-between items-center">
    <%= f.label :email, "Email", class: "block text-sm font-bold text-gray-700" %>
    <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
      Valid
      <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
    </p>
  </div>
  <div class="mt-1">
    <%= f.text_field :email, class: "autofill-color block placeholder:text-slate-400 w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", data: { "form--validator-target": "email"}, placeholder: "you@email.com" %>
  </div>
</div>
<div class="sm:col-span-2">
  <div class="flex justify-between items-center">
    <%= f.label :message, "Message", class: "block text-sm font-bold text-gray-700" %>
    <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
      Valid
      <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
    </p>
    <p class="hidden text-sm font-bold text-red-400 item-animate-right" data-form--validator-target="invalidMessage">
      <%= inline_svg_tag("feedback/exclamation.svg", class: "text-red-400 w-4 h-4 inline-block", aria_hidden: true) %>
      (25 - 500 characters)
    </p>
  </div>
  <div class="mt-1">
    <%= f.text_area :message, rows: 4, class: "block w-full placeholder:text-slate-400 rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 shadow-md", data: { "form--validator-target": "message" }, placeholder: "I'm having trouble understanding Linked Lists and I would appreciate little help with my Rails config 💪" %>
  </div>
</div>
<%= render partial: "requests/form_components/calendar", locals: { f: f } %>
<div class="sm:col-span-2 place-self-center w-3/4">
  <%= f.submit "Submit", class: "cursor-pointer w-full inline-flex items-center justify-center rounded-md px-6 py-3 text-base border-4 border-transparent font-bold text-black shadow-md scale-95 transition ease-in-out bg-transparent hover:border-green-200 hover:scale-90 hover:bg-green-300 hover:text-white hover:font-black duration-300" %>
</div>

app/views/requests/form_components/_title.html.erb
<div class="text-center">
  <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl flex items-center justify-center">
    1:1 Coding Session
    <%= inline_svg_tag "extra/terminal.svg", class: "inline-block w-11 h-11 ml-1" %>
  </h2>
  <p class="mt-4 text-lg leading-6 text-gray-500">Lectures, coding guidance, project reviews, and more.</p>
</div>

app/views/reviews/_new.html.erb
<div class="absolute inset-0">
  <div class="absolute inset-y-0 left-0 w-1/2 bg-gray-50"></div>
</div>
<div class="relative mx-auto max-w-7xl lg:grid lg:grid-cols-5">
  <%= render "reviews/form_components/title" %>
  <div class="bg-white py-16 px-6 lg:col-span-3 lg:py-24 lg:px-8 xl:pl-12">
    <div class="mx-auto max-w-lg lg:max-w-none">
      <%= form_with model: review, url: reviews_path, method: :post, local: true, data: { controller: "form--validator", "form--validator-target": "form" } do |f| %>
        <%= render partial: "reviews/form_components/fields", locals: { f: f } %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/create.turbo_stream.erb
<%= turbo_stream.replace "review_tab" do %>
  <%= turbo_frame_tag "review_tab" do %>
    <div class="relative bg-white" data-tabs-target="reviewTab">
      <%= render partial: "reviews/new", locals: {review: @review} %>
    </div>
  <% end %>
<% end %>



<%= turbo_stream.replace "flash_messages", partial: "shared/flash_messages" %>

app/views/reviews/form_components/_fields.html.erb
<div class="grid grid-cols-1 gap-y-6  place-items-stretch">
  <div class="grid grid-cols-2 gap-3">
    <div>
      <div class="flex justify-between items-center">
        <%= f.label :first_name, "First name", class: "block text-sm font-bold text-gray-700" %>
        <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
          Valid
          <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
        </p>
      </div>
      <%= f.text_field :first_name, class: "block w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", data: { "form--validator-target": "firstName" } %>
    </div>
    <div>
      <div class="flex justify-between items-center">
        <%= f.label :last_name, "Last name", class: "block text-sm font-bold text-gray-700" %>
        <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
          Valid
          <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
        </p>
      </div>
      <%= f.text_field :last_name, class: "block w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", data: { "form--validator-target": "lastName" } %>
    </div>
  </div>
  <div>
  <div class="flex justify-between items-center">
      <%= f.label :email, "Email", class: "block text-sm font-bold text-gray-700" %>
      <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
        Valid
        <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
      </p>
  </div>
  <%= f.text_field :email, class: "autofill-color block placeholder:text-slate-400 w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", data: { "form--validator-target": "email"}, placeholder: "you@email.com" %>
  </div>
  <div>
    <div class="flex justify-between items-center">
      <%= f.label :message, "Message", class: "block text-sm font-bold text-gray-700" %>
      <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
        Valid
        <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
      </p>
      <p class="hidden text-sm font-bold text-red-400 item-animate-right" data-form--validator-target="invalidMessage">
        <%= inline_svg_tag("feedback/exclamation.svg", class: "font-bold text-red-400 w-4 h-4 inline-block", aria_hidden: true) %>
        (25 - 500 characters)
      </p>
    </div>
    <%= f.text_area :message, rows: 4, class: "block w-full placeholder:text-slate-400 rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 shadow-md", data: { "form--validator-target": "message" }, placeholder: "How was your experience? 🍀" %>
  </div>
  <div>
    <div class="flex justify-between items-center">
      <%= f.label :rating, "Leave your rating", class: "block text-sm font-bold text-gray-700" %>
      <p class="hidden text-sm font-bold text-emerald-400 item-animate-right" data-form--validator-target="validField">
        Valid
        <%= inline_svg_tag("feedback/line-check.svg", class: "text-green-400 w-4 h-4 inline-block", aria_hidden: true) %>
      </p>
    </div>
    <%= f.select :rating, Review::RATINGS.map { |rating| [rating[0], rating[1]] }, {}, class: "block w-full rounded-md border-transparent border-2 focus:bg-white focus:border-transparent focus:ring-transparent py-3 px-4 drop-shadow-md  transition ease-in-out delay-100", data: { "form--validator-target": "subject" } %>
  </div>
  <div class="place-self-center w-3/4 lg:place-self-start lg:w-1/4">
    <%= f.submit "Submit", class: "cursor-pointer w-full inline-flex items-center justify-center rounded-md px-6 py-3 text-base border-4 border-transparent font-bold text-black shadow-md scale-95 transition ease-in-out bg-transparent hover:border-green-200 hover:scale-90 hover:bg-green-300 hover:text-white hover:font-black duration-300", type: "submit" %>
  </div>
</div>

app/views/reviews/form_components/_title.html.erb
<div class="bg-gray-50 py-16 px-6 lg:col-span-2 lg:px-8 lg:py-24 xl:pr-12">
  <div class="mx-auto max-w-lg">
    <h2 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Did you have a class recently?</h2>
    <p class="mt-3 text-lg leading-6 text-gray-500"> Please, leave your review.</p>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<%= turbo_frame_tag "flash_messages" do %>
  <% flash.each do |type, values| %>
      <%= render Flash::Component.new(message: values[:message], body: values[:body], type: type) %>
  <% end %>
<% end %>